config/routes.rb
Rails.application.routes.draw do
# User Routes
  get 'all_users' => 'admin#all_users'

  get 'show_user' => 'admin#show_user'

  post 'edit_user' => 'admin#edit_user'
  
  post 'delete_user' => 'admin#delete_user'
  
  get 'delete_user' => 'admin#delete_user'
  
  # Cart Routes
  post 'add_to_cart' => 'cart#add_to_cart'

  get 'view_order' => 'cart#view_order'

  get 'checkout' => 'cart#checkout'

  get 'edit_line_item' => 'cart#edit_line_item'

  post 'edit_line_item' => 'cart#edit_line_item'

  post 'delete_line_item' => 'cart#delete_line_item'
  
  get 'delete_line_item' => 'cart#delete_line_item'

  post 'order_complete' => 'cart#order_complete'


# Storefront Routes
  root 'storefront#all_shoes'

  get 'categorical' => 'storefront#shoes_by_category'

  get 'branding' => 'storefront#shoes_by_brand'

  get 'sizes' => 'storefront#shoes_by_size'

  get 'contact_us' => 'storefront#contact_us'

  

  devise_for :users
  resources :shoes

   get 'backroom' => 'shoes#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  def add_to_cart
    if params[:quantity].to_i == 0
      flash[:notice] = "Please enter a valid quantity to add to cart!"
      redirect_back(fallback_location: root_path)

    else

    	line_item = LineItem.create(shoe_id: params[:shoe_id], quantity: params[:quantity])

    	line_item.update(line_item_total: (line_item.quantity * line_item.shoe.price))

    	redirect_back(fallback_location: root_path)
    end
  end

  def view_order
  	@line_items = LineItem.all
  end

  def checkout
    line_items = LineItem.all
    @order = Order.create(user_id: current_user.id, subtotal: 0)

    puts "********************************"

    line_items.each do |line_item|
      line_item.shoe.update(quantity: (line_item.shoe.quantity - line_item.quantity))
      @order.order_items[line_item.shoe_id] = line_item.quantity 
      @order.subtotal += line_item.line_item_total
    end
  @order.save

  @order.update(sales_tax: (@order.subtotal * 0.08))
  @order.update(grand_total: (@order.sales_tax + @order.subtotal))

  line_items.destroy_all
  end

  def order_complete
    @order = Order.find(params[:order_id])
    @amount = (@order.grand_total.to_f.round(2) * 100).to_i

    customer = Stripe::Customer.create(
      :email => current_user.email,
      :card => params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      :customer => customer.id,
      :amount => @amount,
      :description => 'Fire from Phresh Kickz',
      :currency => 'usd'
    )

    rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to cart_path
  end

  def edit_line_item
    # @order = current_order
    line_item = LineItem.find_by(shoe_id: params[:shoe_id].to_i)
    line_item.update(quantity: params[:quantity].to_i)
    line_item.update(line_item_total: line_item.quantity * line_item.shoe.price)

    redirect_back(fallback_location: view_order) 

  end 

  def delete_line_item
    # @order = current_order
    line_item = LineItem.where(shoe_id: params[:shoe_id].to_i).first
    line_item.destroy
    redirect_back(fallback_location: view_order)  
  end
end

app/helpers/cart_helper.rb
module CartHelper
end

app/views/cart/add_to_cart.html.erb
<h1>Cart#add_to_cart</h1>
<p>Find me in app/views/cart/add_to_cart.html.erb</p>

app/views/cart/checkout.html.erb
<h2>Thanks for shopping with us!</h2>

<div class="panel panel-success">
  <div class="panel-header">
    <div class="panel-body">
      <div class="well">
        <p>Let's review your order:</p>
        <table class="table">
          <thead>
              <tr>
                <th>Item & Quantity</th>
              </tr>
          </thead>

          <tbody>
            <% @order.order_items.each do |k,v| %>
            <tr>
              <td><%= Shoe.find(k).name %>, <%= v %></td>
              <% end %>
            </tr> 
          </tbody>
        </table>

        <br />
        
        <p>
        <strong>Subtotal: <%= number_to_currency @order.subtotal %></strong>  
        </p>

        <p>
        <strong>Sales Tax: <%= number_to_currency @order.sales_tax %></strong>  
        </p>

        <div>
          <%= form_tag order_complete_path do %>
            <article>
              <label class="amount">
                <span><strong>Order Total: </strong><%= number_to_currency @order.grand_total %></span>
              </label>
            </article>
            <div>
              <%= hidden_field_tag :order_id, @order.id %>
            </div>

            <script src="http://checkout.stripe.com/checkout.js" class="stripe-button" data-key="<%= Rails.configuration.stripe[:publishable_key] %>" data-description="Order #<%= @order.id %>" data-amount="<%= (@order.grand_total.to_f.round(2) * 100) %>"></script>
          <% end %>
        </div>
        

app/views/cart/order_complete.html.erb
<div class="panel panel-success">
	<div class="panel-header">
		<div class="panel-body">
			<div class="well">
			<h2>Thank you for your order!</h2>
				<h4>Grab a pen or screenshot the below info:</h4>
				<p>
				  Your order # is: #<%= @order.id %>
				  If you have any questions regarding this order contact us at:<%= mail_to "customerservice@phreshkickz.com" %>
				  Your order #<%= @order.id %> will be shipping as soon as possible, and thank you <%= @order.user.name %>, for choosing Phresh Kickz!
				</p>
			</div>
		</div>
	</div>
</div>

app/views/cart/view_order.html.erb
<h2><%= current_user.name %>'s Cart</h2>

<div class="panel panel-success">
	<div class="panel-header">
		<div class="panel-body">
			<div class="well">
<table class="table">
	<thead>
		<tr>
			<th>Item</th>
			<th>Name</th>
			<th>Price</th>
			<th>Quantity</th>
			<th>Subtotal</th>

<tbody>
  <% @line_items.each do |line_item| %>
  <tr>
  	<td><%= image_tag line_item.shoe.image.thumb, class: "img-rounded" %></td>
    <td><%= line_item.shoe.name %></td>
    <td><%= number_to_currency line_item.shoe.price %></td>
    <td>Qty: <%= line_item.quantity %></td>
    <td>Subtotal: <%= number_to_currency line_item.line_item_total %></td>
    <%= form_tag edit_line_item_path do %>
	        <%= hidden_field_tag :order_id, line_item.order_id %>
	        <%= hidden_field_tag :shoe_id, line_item.shoe_id %>
	        <td><%= number_field_tag :quantity, nil, min: 0, max: line_item.shoe.quantity, class: "form-control" %></td>
	        <td><%= submit_tag "Edit Quantity", class: "btn btn-primary" %></td>
	       <% end %> 
	        <td><%= link_to "Delete From Cart", delete_line_item_path(shoe_id: line_item.shoe_id, order_id: line_item.order_id), class: "btn btn-danger" %></td>
  <% end %>
	</tr>
</tbody>
</table>
			</div>
		</div>
	</div>
</div>


<br />
<br />

<div>
  <%= link_to "Proceed to Checkout?", checkout_path, class: "btn btn-success" %>
</div>