config/routes.rb
Rails.application.routes.draw do
# User Routes
  get 'all_users' => 'admin#all_users'

  get 'show_user' => 'admin#show_user'

  post 'edit_user' => 'admin#edit_user'
  
  post 'delete_user' => 'admin#delete_user'
  
  get 'delete_user' => 'admin#delete_user'
  
  # Cart Routes
  post 'add_to_cart' => 'cart#add_to_cart'

  get 'view_order' => 'cart#view_order'

  get 'checkout' => 'cart#checkout'

  get 'edit_line_item' => 'cart#edit_line_item'

  post 'edit_line_item' => 'cart#edit_line_item'

  post 'delete_line_item' => 'cart#delete_line_item'
  
  get 'delete_line_item' => 'cart#delete_line_item'

  post 'order_complete' => 'cart#order_complete'


# Storefront Routes
  root 'storefront#all_shoes'

  get 'categorical' => 'storefront#shoes_by_category'

  get 'branding' => 'storefront#shoes_by_brand'

  get 'sizes' => 'storefront#shoes_by_size'

  get 'contact_us' => 'storefront#contact_us'

  

  devise_for :users
  resources :shoes

   get 'backroom' => 'shoes#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/admin/all_users.html.erb
<h1>Site Members:</h1>
<br />


<table class="table">
	<thead>
		<tr>
			<th>Name</th>
			<th>Email</th>
			<th>Role</th>
		</tr>
	</thead>

	<tbody>
<% @users.each do |u| %>
	<tr>
		<td><%= u.name %></td>
		<td><%= u.email %></td>
		<td><%= u.role.upcase %></td>
		<td><%= link_to "Select User", show_user_path(id: u.id), class: "btn btn-warning" %></td>
<% end %>
	</tr>
	</tbody>
</table>


<%= link_to "Home", root_path, class: "btn btn-danger" %>

app/views/admin/edit_user.html.erb
<h1>Admin#edit_user</h1>
<p>Find me in app/views/admin/edit_user.html.erb</p>

app/views/admin/show_user.html.erb
<h1>Profile for <%= @user.email %>:</h1>

<table class="table">
	<thead>
		<tr>
			<th>Email: </th>
			<th>Role: </th>	
			<th>Action: </th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td><%= @user.email %></td>
			<td><%= @user.role %></td>	
			<td>
				<% if can? :manage, User %>
					<%= form_tag edit_user_path do %>
						<%= select_tag(:role, options_for_select([ "seller", "buyer" ]), :prompt => "Please select") %>
			  		<%= hidden_field_tag :id, @user.id %>
			  		<%= submit_tag "Update Role", class: "btn btn-warning" %>
			  		<%= link_to "Delete User", delete_user_path(id: @user.id), data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
					<% end %>
				<% end %>	
			</td>
		</tr>	
	</tbody>
</table>

<%= link_to "Back", all_users_path, class: "btn btn-warning" %>