config/routes.rb
Rails.application.routes.draw do
# User Routes
  get 'all_users' => 'admin#all_users'

  get 'show_user' => 'admin#show_user'

  post 'edit_user' => 'admin#edit_user'
  
  post 'delete_user' => 'admin#delete_user'
  
  get 'delete_user' => 'admin#delete_user'
  
  # Cart Routes
  post 'add_to_cart' => 'cart#add_to_cart'

  get 'view_order' => 'cart#view_order'

  get 'checkout' => 'cart#checkout'

  get 'edit_line_item' => 'cart#edit_line_item'

  post 'edit_line_item' => 'cart#edit_line_item'

  post 'delete_line_item' => 'cart#delete_line_item'
  
  get 'delete_line_item' => 'cart#delete_line_item'

  post 'order_complete' => 'cart#order_complete'


# Storefront Routes
  root 'storefront#all_shoes'

  get 'categorical' => 'storefront#shoes_by_category'

  get 'branding' => 'storefront#shoes_by_brand'

  get 'sizes' => 'storefront#shoes_by_size'

  get 'contact_us' => 'storefront#contact_us'

  

  devise_for :users
  resources :shoes

   get 'backroom' => 'shoes#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/shoe.rb
class Shoe < ApplicationRecord
	mount_uploader :image, ImageUploader

	belongs_to :user
	belongs_to :category
	has_many :sizes

	
end

app/controllers/shoes_controller.rb
class ShoesController < ApplicationController
  before_action :set_shoe, only: [:show, :edit, :update, :destroy]

  before_action :authenticate_user!, except: [:show]

  # GET /shoes
  # GET /shoes.json
  def index
    @shoes = Shoe.order(:category_id)
  end

  # GET /shoes/1
  # GET /shoes/1.json
  def show
  end

  # GET /shoes/new
  def new
    @shoe = Shoe.new
    @categories = Category.all
  end

  # GET /shoes/1/edit
  def edit
    @categories = Category.all
  end

  # POST /shoes
  # POST /shoes.json
  def create
    @shoe = Shoe.new(shoe_params)

    respond_to do |format|
      if @shoe.save
        format.html { redirect_to backroom_path, notice: 'Shoe was successfully added to inventory.' }
        format.json { render :show, status: :created, location: @shoe }
      else
        format.html { render :new }
        format.json { render json: @shoe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shoes/1
  # PATCH/PUT /shoes/1.json
  def update

    respond_to do |format|
      if @shoe.update(shoe_params)
      
        format.html { redirect_to backroom_path, notice: 'Inventory was successfully updated.' }
        format.json { render :show, status: :ok, location: @shoe }
      else
        format.html { render :edit }
        format.json { render json: @shoe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shoes/1
  # DELETE /shoes/1.json
  def destroy
    @shoe.destroy
    respond_to do |format|
      format.html { redirect_to shoes_url, notice: 'Shoe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def add_sizes
    @sizes = Size.find_by(:name)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shoe
      @shoe = Shoe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shoe_params
      params.require(:shoe).permit(:name, :price, :size, :quantity, :description, :brand, :category_id, :image, :user_id)
    end
end

app/helpers/shoes_helper.rb
module ShoesHelper
end

app/views/shoes/_form.html.erb
<%= form_with(model: shoe, local: true) do |form| %>
  <% if shoe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(shoe.errors.count, "error") %> prohibited this shoe from being saved:</h2>

      <ul>
      <% shoe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="form-group">
  <strong>Upload Product Image: </strong>
  <%= form.file_field :image %>
</div>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, id: :shoe_name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :price %>
    <%= form.text_field :price, id: :shoe_price, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :size %>
    <%= form.number_field :size, value: nil, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :quantity %>
    <%= form.number_field :quantity, value: nil, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, id: :shoe_description, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :brand %>
    <%= form.text_field :brand, id: :shoe_brand, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :category_id %>
    <%= form.select :category_id, @categories.collect { |c| [ c.name, c.id ]}, {include_blank: "Please select a category" } %>
  </div>

  <div class="field">
    <%= form.hidden_field :user_id, value: current_user.id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/shoes/edit.html.erb
<h1>Editing Shoe</h1>

<%= render 'form', shoe: @shoe %>

<%= link_to 'Show', @shoe %> |
<%= link_to 'Back', shoes_path %>

app/views/shoes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Inventory</h1>

<br />

<table class="table">
  <thead>
    <tr>
      <th>Image</th>
      <th>Name</th>
      <th>Price</th>
      <th>Size</th>
      <th>Quantity</th>
      <th>Description</th>
      <th>Brand</th>
      <th>Category</th>
    </tr>
  </thead>

  <tbody>
    <% @shoes.each do |shoe| %>
      <tr>
        <td><%= image_tag shoe.image.thumb, class: "img-rounded" %></td>
        <td><%= shoe.name %></td>
        <td><%= number_to_currency shoe.price %></td>
        <td><%= shoe.size %></td>
        <td><%= shoe.quantity %></td>
        <td><%= shoe.description %></td>
        <td><%= shoe.brand %></td>
        <td><%= shoe.category.name %></td>
      <% if can? :update, Shoe %>
       <% if shoe.user_id == current_user.id %>
        <td><%= link_to 'Edit', edit_shoe_path(shoe), class: "btn btn-warning" %></td>
        <td><%= link_to 'Destroy', shoe, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></td>
        <% end %>
      <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if can? :create, Shoe %>
  <%= link_to 'New Shoe', new_shoe_path, class: "btn btn-success" %>
<% end %>

app/views/shoes/new.html.erb
<h1>New Shoe</h1>

<%= render 'form', shoe: @shoe %>

<%= link_to 'Back', shoes_path %>

app/views/shoes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <%= image_tag @shoe.image.url, class: "img-rounded" %>
</p>


<p>
  <strong>Name:</strong>
  <%= @shoe.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @shoe.price %>
</p>

<p>
  <strong>Description:</strong>
  <%= @shoe.description %>
</p>

<p>
  <strong>Brand:</strong>
  <%= @shoe.brand %>
</p>

<p>
  <strong>Category:</strong>
  <%= @shoe.category_id %>
</p>

<p>
  <strong>Seller:</strong>
  <%= @shoe.user.name %>
</p>



<%= link_to 'Edit', edit_shoe_path(@shoe) %> |
<%= link_to 'Back', shoes_path %>