config/routes.rb
Rails.application.routes.draw do
# User Routes
  get 'all_users' => 'admin#all_users'

  get 'show_user' => 'admin#show_user'

  post 'edit_user' => 'admin#edit_user'
  
  post 'delete_user' => 'admin#delete_user'
  
  get 'delete_user' => 'admin#delete_user'
  
  # Cart Routes
  post 'add_to_cart' => 'cart#add_to_cart'

  get 'view_order' => 'cart#view_order'

  get 'checkout' => 'cart#checkout'

  get 'edit_line_item' => 'cart#edit_line_item'

  post 'edit_line_item' => 'cart#edit_line_item'

  post 'delete_line_item' => 'cart#delete_line_item'
  
  get 'delete_line_item' => 'cart#delete_line_item'

  post 'order_complete' => 'cart#order_complete'


# Storefront Routes
  root 'storefront#all_shoes'

  get 'categorical' => 'storefront#shoes_by_category'

  get 'branding' => 'storefront#shoes_by_brand'

  get 'sizes' => 'storefront#shoes_by_size'

  get 'contact_us' => 'storefront#contact_us'

  

  devise_for :users
  resources :shoes

   get 'backroom' => 'shoes#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PersonalEcommerce</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>

  <center>
    <h1>Phresh Kickz</h1>
  </center>
  <br />

    <!-- Nav bar -->
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <!-- Insert Company Image Here -->
      <%= link_to fa_icon("Home", text: "Home", class: "fa fa-home fa-lg"),root_path, class: "navbar-brand" %>
    </div>
      <!-- End -->
    <!-- Collect the nav links -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Brands<span class="caret"></span></a>
            <ul class="dropdown-menu">
              <% @brands.each do |brand| %>
                <li><%= link_to brand, branding_path(brand: brand) %></li>
              <% end %>      
            </ul>
        </li> 

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Categories<span class="caret"></span></a>
            <ul class="dropdown-menu">
              <% @categories.each do |category| %>
                <li><%= link_to category.name, categorical_path(category_id: category.id) %></li>
              <% end %>
            </ul>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-left">
        <li><%= link_to fa_icon("Contact Us", text: "Contact Us", class: "fa fa-inbox"), contact_us_path %></li>
      </ul>
    <!-- End -->
    <!-- Right Hand Side links and dropdown -->
    <% if user_signed_in? %>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Signed In As: <%= current_user.email %> <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to fa_icon("View Cart", text: "View Cart", class: "fa fa-shopping-basket"), view_order_path %>
            <li><%= link_to fa_icon("Edit Profile", text: "Edit Profile", class: "fa fa-user-circle-o"), edit_user_registration_path %></li>
            <li><%= link_to fa_icon("Sign Out", text: "Sign Out", class: "fa fa-hand-peace-o"), destroy_user_session_path, method: :delete %></li>
          </ul>
        </li>
      <% if can? :manage, Shoe %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Admin<span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to fa_icon("Inventory", text: "Inventory", class: "fa fa-bar-chart"), backroom_path %></li>
            <% if can? :manage, :all %> 
              <li><%= link_to fa_icon("All Users", text: "All Users", class: "fa fa-users"), all_users_path %></li>
            <% end %>
            </ul>
          </li>
      <% end %>
      </ul>
    <% else %>
      <ul class="nav navbar-nav navbar-right">
        <li><%=link_to fa_icon("Sign In / Sign Up", text: "Sign In / Sign Up", class: "fa fa-sign-in"), new_user_session_path %></li>
      </ul>
    <% end %>
      

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<!-- end -->





  



  <div class="container">
    <%= yield %>
  </div>
  





<nav class="navbar navbar-default navbar-fixed-bottom">
  <div class="container">
    <br/>
    <center>
      <p><a href="#"><i class="fa fa-instagram fa-lg"></i></a>
        <a href="#"><i class="fa fa-facebook-square fa-lg"></i></a>
        <a href="#"><i class="fa fa-twitter fa-lg"></i></a>
        <a href="#"><i class="fa fa-envelope fa-lg"></i></a></p>
        Phresh Kickz copyright&copy 2017
    </center>
    <br />
  </div>
</nav>

<!-- api for google maps -->
<script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['google_api_key'] %>">
</script>

  </body>
</html>